name: Build mkcert docker
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
env:
  docker_registry: registry.hub.docker.com
  docker_organization: vleedev
  docker_repository: filosottile_mkcert
  docker_login: vleedev
  docker_tag: "${{ inputs.version }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: "${{ env.docker_login }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
      - 
        name: Docker Build and Push
        run: |
          docker_image="${{ env.docker_registry }}/${{ env.docker_organization }}/${{ env.docker_repository }}:${{ env.docker_tag }}"
          # Check image exists
          docker_image_exist=0
          if ! docker pull "${docker_image}" > /dev/null 2>&1; then
              docker_image_exist=1
          fi

          if [[ ${docker_image_exist} -eq 0 ]]; then
              echo "Image exists ${docker_image}"
              exit 1
          fi

          # Build image
          docker build -t "${docker_image}" --target=app --build-arg MKCERT_VERSION="${{ inputs.version }}" .
          # Push image
          docker push "${docker_image}"
