name: Monitor FiloSottile/mkcert and Trigger Workflow on New Release

on:
  workflow_dispatch: # Allow to run manually
  schedule:
    - cron: "0 0 * * *"   # Run every day at midnight UTC

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Latest Release
        id: check_release
        uses: actions/github-script@v6
        with:
          result-encoding: string
          retries: 3
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'FiloSottile',
              repo: 'mkcert'
            });
            const latestRelease = response.data;
            console.log('Latest Release:', latestRelease.tag_name);
            // return to set 'result' key in outputs
            // Take by: steps.check_release.outputs.result
            return latestRelease.tag_name
      - name: Trigger workflow
        id: trigger_workflow
        if: "${{ steps.check_release.outputs.result }}"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          retries: 3
          script: |
              // Trigger workflow here
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'main',
                workflow_id: 'docker_mkcert.yml',
                inputs: {
                  version: "${{ steps.check_release.outputs.result }}",
                }
              });