name: Monitor FiloSottile/mkcert and Trigger Workflow on New Release

on:
  workflow_dispatch: # Allow to run manually
  schedule:
    - cron: "0 0 * * *"   # Run every day at midnight UTC

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Latest Release
        id: release
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'FiloSottile',
              repo: 'mkcert'
            });

            console.log(response);