name: Monitor FiloSottile/mkcert and Trigger Workflow on New Release

on:
  workflow_dispatch: # Allow to run manually
  schedule:
    - cron: "0 0 * * *"   # Run every day at midnight UTC

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check Latest Release
        id: release
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'FiloSottile',
              repo: 'mkcert'
            });
            const latestRelease = response.data;
            console.log('Latest Release:', latestRelease.tag_name);
            // Trigger workflow here
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              workflow_id: 'docker_mkcert.yml',
              inputs: {
                version: latestRelease.tag_name,
              }
            });